# 1. 데이터 준비

In [11]:
import os
import datetime
import pandas as pd
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
import pickle
import warnings
warnings.filterwarnings("ignore")

In [12]:
df = pd.read_csv('csv_data/cycles_50_final_dataset.csv', infer_datetime_format=True)

In [13]:
df

,BSM-p,BSM-m,BSM-c,Datetime,Voltage-p,Voltage-m,Voltage-c,Current,Temperature-p,Temperature-m,State,Capacity,SOC,SOH,Cycles
0,SN-P10001,SN-M10001,SN-C10001,2023-05-01 04:00:00,382.256579,50.082072,4.143506,140.626825,17.058245,19.318245,1,NaN,0.0,NaN,1
1,SN-P10001,SN-M10001,SN-C10002,2023-05-01 04:00:00,382.256579,50.082072,3.263506,140.626825,17.058245,19.318245,1,NaN,0.0,NaN,1
2,SN-P10001,SN-M10001,SN-C10003,2023-05-01 04:00:00,382.256579,50.082072,3.253506,140.626825,17.058245,19.318245,1,NaN,0.0,NaN,1
3,SN-P10001,SN-M10001,SN-C10004,2023-05-01 04:00:00,382.256579,50.082072,4.803506,140.626825,17.058245,19.318245,1,NaN,0.0,NaN,1
4,SN-P10001,SN-M10001,SN-C10005,2023-05-01 04:00:00,382.256579,50.082072,3.683506,140.626825,17.058245,19.318245,1,NaN,0.0,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2110459,SN-P10001,SN-M10008,SN-C10092,2023-05-16 10:23:00,363.222733,44.212842,4.494403,62.126966,36.590995,37.920995,2,1.767364,0.0,0.951994,50
2110460,SN-P10001,SN-M10008,SN-C10093,2023-05-16 10:23:00,363.222733,44.212842,4.244403,62.126966,36.590995,37.920995,2,1.767364,0.0,0.951994,50
2110461,SN-P10001,SN-M10008,SN-C10094,2023-05-16 10:23:00,363.222733,44.212842,4.534403,62.126966,36.590995,37.920995,2,1.767364,0.0,0.951994,50
2110462,SN-P10001,SN-M10008,SN-C10095,2023-05-16 10:23:00,363.222733,44.212842,2.894403,62.126966,36.590995,37.920995,2,1.767364,0.0,0.951994,50
2110463,SN-P10001,SN-M10008,SN-C10096,2023-05-16 10:23:00,363.222733,44.212842,2.984403,62.126966,36.590995,37.920995,2,1.767364,0.0,0.951994,50

In [14]:
df['Datetime'] = pd.to_datetime(df['Datetime'])

In [15]:
fuel_cells_df_state_1 = df[df["State"] == 1]

In [16]:
fuel_cells_df = df[df["State"] == 2]

In [17]:
fuel_cells_df_state_1

,BSM-p,BSM-m,BSM-c,Datetime,Voltage-p,Voltage-m,Voltage-c,Current,Temperature-p,Temperature-m,State,Capacity,SOC,SOH,Cycles
0,SN-P10001,SN-M10001,SN-C10001,2023-05-01 04:00:00,382.256579,50.082072,4.143506,140.626825,17.058245,19.318245,1,NaN,0.0,NaN,1
1,SN-P10001,SN-M10001,SN-C10002,2023-05-01 04:00:00,382.256579,50.082072,3.263506,140.626825,17.058245,19.318245,1,NaN,0.0,NaN,1
2,SN-P10001,SN-M10001,SN-C10003,2023-05-01 04:00:00,382.256579,50.082072,3.253506,140.626825,17.058245,19.318245,1,NaN,0.0,NaN,1
3,SN-P10001,SN-M10001,SN-C10004,2023-05-01 04:00:00,382.256579,50.082072,4.803506,140.626825,17.058245,19.318245,1,NaN,0.0,NaN,1
4,SN-P10001,SN-M10001,SN-C10005,2023-05-01 04:00:00,382.256579,50.082072,3.683506,140.626825,17.058245,19.318245,1,NaN,0.0,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899707,SN-P10001,SN-M10008,SN-C10092,2023-05-07 16:11:00,387.291465,47.221433,4.745119,199.564588,20.211440,21.541440,1,NaN,100.0,NaN,50
899708,SN-P10001,SN-M10008,SN-C10093,2023-05-07 16:11:00,387.291465,47.221433,4.495119,199.564588,20.211440,21.541440,1,NaN,100.0,NaN,50
899709,SN-P10001,SN-M10008,SN-C10094,2023-05-07 16:11:00,387.291465,47.221433,4.785119,199.564588,20.211440,21.541440,1,NaN,100.0,NaN,50
899710,SN-P10001,SN-M10008,SN-C10095,2023-05-07 16:11:00,387.291465,47.221433,3.145119,199.564588,20.211440,21.541440,1,NaN,100.0,NaN,50
899711,SN-P10001,SN-M10008,SN-C10096,2023-05-07 16:11:00,387.291465,47.221433,3.235119,199.564588,20.211440,21.541440,1,NaN,100.0,NaN,50

In [18]:
fuel_cells_df.shape

(1210752, 15)

In [19]:
fuel_cells_df.columns

Index(['BSM-p', 'BSM-m', 'BSM-c', 'Datetime', 'Voltage-p', 'Voltage-m',
       'Voltage-c', 'Current', 'Temperature-p', 'Temperature-m', 'State',
       'Capacity', 'SOC', 'SOH', 'Cycles'],
      dtype='object')

In [20]:
fuel_cells_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1210752 entries, 899712 to 2110463
Data columns (total 15 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   BSM-p          1210752 non-null  object
 1   BSM-m          1210752 non-null  object
 2   BSM-c          1210752 non-null  object
 3   Datetime       1210752 non-null  datetime64[ns]
 4   Voltage-p      1210752 non-null  float64
 5   Voltage-m      1210752 non-null  float64
 6   Voltage-c      1210752 non-null  float64
 7   Current        1210752 non-null  float64
 8   Temperature-p  1210752 non-null  float64
 9   Temperature-m  1210752 non-null  float64
 10  State          1210752 non-null  int64
 11  Capacity       1210752 non-null  float64
 12  SOC            1210752 non-null  float64
 13  SOH            1210752 non-null  float64
 14  Cycles         1210752 non-null  int64
dtypes: datetime64[ns](1), float64(9), int64(2), object(3)
memory usage: 147.8+ MB

### 고유값 확인:

In [21]:
for i in fuel_cells_df.columns:
    print(i, ":" , fuel_cells_df[i].nunique())

BSM-p : 1
BSM-m : 8
BSM-c : 96
Datetime : 12612
Voltage-p : 12612
Voltage-m : 100896
Voltage-c : 1196452
Current : 12612
Temperature-p : 12612
Temperature-m : 88284
State : 1
Capacity : 50
SOC : 5435
SOH : 50
Cycles : 50

In [22]:
fuel_cells_df.describe(include=[np.number]).transpose()

,count,mean,std,min,25%,50%,75%,max
Voltage-p,1210752.0,375.025899,5.172463,350.000000,372.558965,374.815995,378.418303,389.722595
Voltage-m,1210752.0,47.170737,1.616109,41.640000,45.999458,46.986557,48.653135,51.015324
Voltage-c,1210752.0,3.952145,0.583012,2.470000,3.476751,3.993219,4.410037,5.201277
Current,1210752.0,66.528497,18.166846,61.598732,62.038783,62.079472,62.122575,140.966492
Temperature-p,1210752.0,27.627580,4.992217,15.000000,24.341441,27.794010,31.349059,40.000000
Temperature-m,1210752.0,28.108830,5.412924,12.020000,24.649109,28.295044,32.029981,42.370000
State,1210752.0,2.000000,0.000000,2.000000,2.000000,2.000000,2.000000,2.000000
Capacity,1210752.0,1.801714,0.030904,1.736091,1.773038,1.804077,1.825582,1.856487
SOC,1210752.0,49.999998,28.982278,0.000000,24.867500,50.000000,75.132500,100.000000
SOH,1210752.0,0.970496,0.016647,0.935149,0.955050,0.971769,0.983353,1.000000
Cycles,1210752.0,29.154853,14.408357,1.000000,17.000000,32.000000,41.000000,50.000000

In [23]:
# Missing values:
def missingValue(df):
    #Identifying Missing data.
    total_null = df.isnull().sum().sort_values(ascending = False)
    percent = ((df.isnull().sum()/len(df))*100).sort_values(ascending = False)
    print(f"Total records in our data =  {df.shape[0]} where missing values are as follows:")

    missing_data = pd.concat([total_null,percent.round(2)],axis=1,keys=['Total Missing','In Percent'])
    return missing_data

In [24]:
missing_df = missingValue(fuel_cells_df)
missing_df[missing_df['Total Missing'] > 0]

Total records in our data =  1210752 where missing values are as follows:

Empty DataFrame
Columns: [Total Missing, In Percent]
Index: []

In [25]:
#fuel_cells_df['Datetime'] = fuel_cells_df['Datetime'].astype('int64')
#fuel_cells_df['Datetime'].head()

In [26]:
# copy before mormalization and after datetime converson to int
fuel_cells_df_copy = fuel_cells_df.copy()

In [27]:
cols = ['Voltage-p', 'Voltage-m', 'Voltage-c',
        'Current', 'Temperature-p', 'Temperature-m', 'Capacity','Cycles']   

mm_scaler = MinMaxScaler()

fuel_cells_df_copy[cols] = mm_scaler.fit_transform(fuel_cells_df_copy[cols])
fuel_cells_df_copy.head()

,BSM-p,BSM-m,BSM-c,Datetime,Voltage-p,Voltage-m,Voltage-c,Current,Temperature-p,Temperature-m,State,Capacity,SOC,SOH,Cycles
899712,SN-P10001,SN-M10001,SN-C10001,2023-05-07 16:12:00,0.570595,0.77258,0.576140,0.007841,0.649481,0.707645,2,1.0,100.0,1.0,0.0
899713,SN-P10001,SN-M10001,SN-C10002,2023-05-07 16:12:00,0.570595,0.77258,0.253947,0.007841,0.649481,0.707645,2,1.0,100.0,1.0,0.0
899714,SN-P10001,SN-M10001,SN-C10003,2023-05-07 16:12:00,0.570595,0.77258,0.250286,0.007841,0.649481,0.707645,2,1.0,100.0,1.0,0.0
899715,SN-P10001,SN-M10001,SN-C10004,2023-05-07 16:12:00,0.570595,0.77258,0.817786,0.007841,0.649481,0.707645,2,1.0,100.0,1.0,0.0
899716,SN-P10001,SN-M10001,SN-C10005,2023-05-07 16:12:00,0.570595,0.77258,0.407721,0.007841,0.649481,0.707645,2,1.0,100.0,1.0,0.0

In [28]:
fuel_cells_df_copy['Cycles'].unique()

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [29]:
from sklearn.ensemble import IsolationForest

In [30]:
flag_df = pd.DataFrame()
flag_df_final = pd.DataFrame()

In [31]:
fuel_cells_df_copy

,BSM-p,BSM-m,BSM-c,Datetime,Voltage-p,Voltage-m,Voltage-c,Current,Temperature-p,Temperature-m,State,Capacity,SOC,SOH,Cycles
899712,SN-P10001,SN-M10001,SN-C10001,2023-05-07 16:12:00,0.570595,0.772580,0.576140,0.007841,0.649481,0.707645,2,1.00000,100.0,1.000000,0.0
899713,SN-P10001,SN-M10001,SN-C10002,2023-05-07 16:12:00,0.570595,0.772580,0.253947,0.007841,0.649481,0.707645,2,1.00000,100.0,1.000000,0.0
899714,SN-P10001,SN-M10001,SN-C10003,2023-05-07 16:12:00,0.570595,0.772580,0.250286,0.007841,0.649481,0.707645,2,1.00000,100.0,1.000000,0.0
899715,SN-P10001,SN-M10001,SN-C10004,2023-05-07 16:12:00,0.570595,0.772580,0.817786,0.007841,0.649481,0.707645,2,1.00000,100.0,1.000000,0.0
899716,SN-P10001,SN-M10001,SN-C10005,2023-05-07 16:12:00,0.570595,0.772580,0.407721,0.007841,0.649481,0.707645,2,1.00000,100.0,1.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2110459,SN-P10001,SN-M10008,SN-C10092,2023-05-16 10:23:00,0.332877,0.274427,0.741193,0.006656,0.863640,0.853410,2,0.25975,0.0,0.951994,1.0
2110460,SN-P10001,SN-M10008,SN-C10093,2023-05-16 10:23:00,0.332877,0.274427,0.649661,0.006656,0.863640,0.853410,2,0.25975,0.0,0.951994,1.0
2110461,SN-P10001,SN-M10008,SN-C10094,2023-05-16 10:23:00,0.332877,0.274427,0.755838,0.006656,0.863640,0.853410,2,0.25975,0.0,0.951994,1.0
2110462,SN-P10001,SN-M10008,SN-C10095,2023-05-16 10:23:00,0.332877,0.274427,0.155386,0.006656,0.863640,0.853410,2,0.25975,0.0,0.951994,1.0
2110463,SN-P10001,SN-M10008,SN-C10096,2023-05-16 10:23:00,0.332877,0.274427,0.188338,0.006656,0.863640,0.853410,2,0.25975,0.0,0.951994,1.0

In [32]:
contamination_value = 0.01

# Create a copy of the original DataFrame to avoid modifying it
fuel_cells_df_final = fuel_cells_df_copy.copy()

# Create a variable holding the relevant columns for fitting the model and decision_function
feature_columns = fuel_cells_df_copy.columns.difference(['BSM-p', 'BSM-m', 'BSM-c','Datetime','State', 'Capacity', 'SOC', 'SOH'])

In [33]:
feature_columns

Index(['Current', 'Cycles', 'Temperature-m', 'Temperature-p', 'Voltage-c',
       'Voltage-m', 'Voltage-p'],
      dtype='object')

In [34]:
# Initialize the IsolationForest model with the desired contamination value
model = IsolationForest(n_estimators=200, max_samples='auto', contamination=contamination_value, random_state=42)

In [35]:
# Fit the model with the feature columns
model.fit(fuel_cells_df_final[feature_columns])

IsolationForest(contamination=0.01, n_estimators=200, random_state=42)

In [36]:
# Predict the anomaly scores and add them to the DataFrame
predictions = model.predict(fuel_cells_df_copy[feature_columns])
fuel_cells_df['anomaly_score' + '_' + str(contamination_value)] = predictions

In [37]:
# Compute the decision function scores and add them to the DataFrame
scores = model.decision_function(fuel_cells_df_copy[feature_columns])
fuel_cells_df['scores' + '_' + str(contamination_value)] = scores

In [38]:
fuel_cells_df

,BSM-p,BSM-m,BSM-c,Datetime,Voltage-p,Voltage-m,Voltage-c,Current,Temperature-p,Temperature-m,State,Capacity,SOC,SOH,Cycles,anomaly_score_0.01,scores_0.01
899712,SN-P10001,SN-M10001,SN-C10001,2023-05-07 16:12:00,372.665516,48.883190,4.043599,62.221067,31.237017,33.497017,2,1.856487,100.0,1.000000,1,1,0.148180
899713,SN-P10001,SN-M10001,SN-C10002,2023-05-07 16:12:00,372.665516,48.883190,3.163599,62.221067,31.237017,33.497017,2,1.856487,100.0,1.000000,1,1,0.121611
899714,SN-P10001,SN-M10001,SN-C10003,2023-05-07 16:12:00,372.665516,48.883190,3.153599,62.221067,31.237017,33.497017,2,1.856487,100.0,1.000000,1,1,0.120506
899715,SN-P10001,SN-M10001,SN-C10004,2023-05-07 16:12:00,372.665516,48.883190,4.703599,62.221067,31.237017,33.497017,2,1.856487,100.0,1.000000,1,1,0.127208
899716,SN-P10001,SN-M10001,SN-C10005,2023-05-07 16:12:00,372.665516,48.883190,3.583599,62.221067,31.237017,33.497017,2,1.856487,100.0,1.000000,1,1,0.139760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2110459,SN-P10001,SN-M10008,SN-C10092,2023-05-16 10:23:00,363.222733,44.212842,4.494403,62.126966,36.590995,37.920995,2,1.767364,0.0,0.951994,50,1,0.073905
2110460,SN-P10001,SN-M10008,SN-C10093,2023-05-16 10:23:00,363.222733,44.212842,4.244403,62.126966,36.590995,37.920995,2,1.767364,0.0,0.951994,50,1,0.082021
2110461,SN-P10001,SN-M10008,SN-C10094,2023-05-16 10:23:00,363.222733,44.212842,4.534403,62.126966,36.590995,37.920995,2,1.767364,0.0,0.951994,50,1,0.073023
2110462,SN-P10001,SN-M10008,SN-C10095,2023-05-16 10:23:00,363.222733,44.212842,2.894403,62.126966,36.590995,37.920995,2,1.767364,0.0,0.951994,50,1,0.055969
2110463,SN-P10001,SN-M10008,SN-C10096,2023-05-16 10:23:00,363.222733,44.212842,2.984403,62.126966,36.590995,37.920995,2,1.767364,0.0,0.951994,50,1,0.060190

In [39]:
fuel_cells_df['anomaly_score_0.01'].value_counts(ascending= True)

-1      12108
 1    1198644
Name: anomaly_score_0.01, dtype: int64

In [40]:
# Assuming fuel_cells_df_final is already a DataFrame
count = fuel_cells_df[(fuel_cells_df['anomaly_score_0.01'] == -1)].groupby('BSM-m')['anomaly_score_0.01'].count()

print(count)

BSM-m
SN-M10001    1449
SN-M10002    2457
SN-M10003    1327
SN-M10004    1378
SN-M10005    1301
SN-M10006    1211
SN-M10007    1223
SN-M10008    1762
Name: anomaly_score_0.01, dtype: int64

In [41]:
# Assuming fuel_cells_df_final is already a DataFrame
count = fuel_cells_df[(fuel_cells_df['anomaly_score_0.01'] == -1)].groupby('BSM-c')['anomaly_score_0.01'].count()

print(count)

BSM-c
SN-C10001    104
SN-C10002    156
SN-C10003    157
SN-C10004    115
SN-C10005    110
            ...
SN-C10092    131
SN-C10093    120
SN-C10094    131
SN-C10095    221
SN-C10096    203
Name: anomaly_score_0.01, Length: 96, dtype: int64

In [42]:
filtered_df = fuel_cells_df[fuel_cells_df['anomaly_score_0.01'] == -1]
count = filtered_df.groupby('BSM-c')['anomaly_score_0.01'].count()

top_5 = count.nlargest(5)

print(top_5)

BSM-c
SN-C10017    427
SN-C10019    403
SN-C10015    326
SN-C10016    227
SN-C10085    224
Name: anomaly_score_0.01, dtype: int64

In [47]:
# 데이터 프레임 합치기
combined_df = pd.concat([fuel_cells_df, fuel_cells_df_state_1])

# 'state'와 'cycle' 열로 정렬하기
df_final = combined_df.sort_values(['State', 'Cycles'])

In [50]:
df_final = df_final.replace({np.nan: None})

In [51]:
df_final

,BSM-p,BSM-m,BSM-c,Datetime,Voltage-p,Voltage-m,Voltage-c,Current,Temperature-p,Temperature-m,State,Capacity,SOC,SOH,Cycles,anomaly_score_0.01,scores_0.01
0,SN-P10001,SN-M10001,SN-C10001,2023-05-01 04:00:00,382.256579,50.082072,4.143506,140.626825,17.058245,19.318245,1,None,0.0,None,1,None,None
1,SN-P10001,SN-M10001,SN-C10002,2023-05-01 04:00:00,382.256579,50.082072,3.263506,140.626825,17.058245,19.318245,1,None,0.0,None,1,None,None
2,SN-P10001,SN-M10001,SN-C10003,2023-05-01 04:00:00,382.256579,50.082072,3.253506,140.626825,17.058245,19.318245,1,None,0.0,None,1,None,None
3,SN-P10001,SN-M10001,SN-C10004,2023-05-01 04:00:00,382.256579,50.082072,4.803506,140.626825,17.058245,19.318245,1,None,0.0,None,1,None,None
4,SN-P10001,SN-M10001,SN-C10005,2023-05-01 04:00:00,382.256579,50.082072,3.683506,140.626825,17.058245,19.318245,1,None,0.0,None,1,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2110459,SN-P10001,SN-M10008,SN-C10092,2023-05-16 10:23:00,363.222733,44.212842,4.494403,62.126966,36.590995,37.920995,2,1.767364,0.0,0.951994,50,1.0,0.073905
2110460,SN-P10001,SN-M10008,SN-C10093,2023-05-16 10:23:00,363.222733,44.212842,4.244403,62.126966,36.590995,37.920995,2,1.767364,0.0,0.951994,50,1.0,0.082021
2110461,SN-P10001,SN-M10008,SN-C10094,2023-05-16 10:23:00,363.222733,44.212842,4.534403,62.126966,36.590995,37.920995,2,1.767364,0.0,0.951994,50,1.0,0.073023
2110462,SN-P10001,SN-M10008,SN-C10095,2023-05-16 10:23:00,363.222733,44.212842,2.894403,62.126966,36.590995,37.920995,2,1.767364,0.0,0.951994,50,1.0,0.055969
2110463,SN-P10001,SN-M10008,SN-C10096,2023-05-16 10:23:00,363.222733,44.212842,2.984403,62.126966,36.590995,37.920995,2,1.767364,0.0,0.951994,50,1.0,0.06019

## 데이터 사전 분리

In [52]:
# pack_log 데이터 프레임 생성 및 중복 제거
df_pack_log = df_final[['BSM-p', 'Voltage-p', 'Current', 'Temperature-p', 'State', 'Capacity', 'SOC', 'SOH', 'Cycles', 'Datetime']]
df_pack_log = df_pack_log.drop_duplicates()

# module_log 데이터 프레임 생성 및 중복 제거
df_module_log = df_final[['BSM-p', 'BSM-m', 'Voltage-m', 'Temperature-m', 'Datetime']]
df_module_log = df_module_log.drop_duplicates()

# cell_log 데이터 프레임 생성 및 중복 제거
df_cell_log = df_final[['BSM-m', 'BSM-c', 'Voltage-c', 'Datetime', 'anomaly_score_0.01' , 'scores_0.01']]
df_cell_log = df_cell_log.drop_duplicates()

In [53]:
df_pack_log.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21984 entries, 0 to 2110368
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   BSM-p          21984 non-null  object
 1   Voltage-p      21984 non-null  object
 2   Current        21984 non-null  object
 3   Temperature-p  21984 non-null  object
 4   State          21984 non-null  int64
 5   Capacity       12612 non-null  object
 6   SOC            21984 non-null  object
 7   SOH            12612 non-null  object
 8   Cycles         21984 non-null  int64
 9   Datetime       21984 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(7)
memory usage: 1.8+ MB

In [54]:
df_module_log.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 175872 entries, 0 to 2110452
Data columns (total 5 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   BSM-p          175872 non-null  object
 1   BSM-m          175872 non-null  object
 2   Voltage-m      175872 non-null  object
 3   Temperature-m  175872 non-null  object
 4   Datetime       175872 non-null  datetime64[ns]
dtypes: datetime64[ns](1), object(4)
memory usage: 8.1+ MB

In [55]:
df_cell_log.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2110464 entries, 0 to 2110463
Data columns (total 6 columns):
 #   Column              Dtype
---  ------              -----
 0   BSM-m               object
 1   BSM-c               object
 2   Voltage-c           object
 3   Datetime            datetime64[ns]
 4   anomaly_score_0.01  object
 5   scores_0.01         object
dtypes: datetime64[ns](1), object(5)
memory usage: 112.7+ MB

### 데이터 mysql에 넣기

In [56]:
import mysql.connector
from mysql.connector import Error

In [57]:
# MySQL 접속 정보
host = 'k8e101.p.ssafy.io'
user = 'root'
password = 'P@ssw0rd12'
database = 'sdilink'

In [59]:
try:
    connection = mysql.connector.connect(host=host, user=user, password=password, database=database, port=3306)
    cursor = connection.cursor()

    for index, row in df_pack_log.iterrows():
        # pack_log 테이블에 데이터 삽입
        pack_log_query = f"""
            INSERT INTO pack_log
            (car_id, pack_code, voltage_p, current, temp_p, status, capacity, soc, soh, cycle, created_at)
            SELECT 1, '{row['BSM-p']}', {row['Voltage-p']}, {row['Current']}, {row['Temperature-p']}, {row['State']},
                   {row['Capacity']}, {row['SOC']}, {row['SOH']}, {row['Cycles']}, '{row['Datetime']}'
            WHERE NOT EXISTS (
                SELECT 1
                FROM pack_log
                WHERE pack_code = '{row['BSM-p']}' AND created_at = '{row['Datetime']}'
            )
        """
        cursor.execute(pack_log_query)
        connection.commit()

    for index, row in df_module_log.iterrows():
        # module_log 테이블에 데이터 삽입
        module_log_query = f"""
            INSERT INTO module_log
            (pack_log_id, module_code, voltage_m, temp_m, created_at)
            SELECT pl.id, '{row['BSM-m']}', {row['Voltage-m']}, {row['Temperature-m']}, '{row['Datetime']}'
            FROM pack_log AS pl
            WHERE pl.pack_code = '{row['BSM-p']}' AND pl.created_at = '{row['Datetime']}' AND
                  NOT EXISTS (
                      SELECT 1
                      FROM module_log
                      WHERE pack_log_id = pl.id AND module_code = '{row['BSM-m']}' AND created_at = '{row['Datetime']}'
                  )
        """
        cursor.execute(module_log_query)
        connection.commit()

    for index, row in df_cell_log.iterrows():
        # cell_log 테이블에 데이터 삽입
        cell_log_query = f"""
            INSERT INTO cell_log
            (module_log_id, cell_code, voltage_c, is_normal, scores_0_01, created_at)
            SELECT ml.id, '{row['BSM-c']}', {row['Voltage-c']}, {row['scores_0.01']}, {row['anomaly_score_0.01']}, '{row['Datetime']}'
            FROM module_log AS ml
            JOIN pack_log AS pl ON ml.pack_log_id = pl.id
            WHERE ml.module_code = '{row['BSM-m']}' AND ml.created_at = '{row['Datetime']}' AND
                  NOT EXISTS (
                      SELECT 1
                      FROM cell_log
                      WHERE module_log_id = ml.id AND cell_code = '{row['BSM-c']}' AND created_at = '{row['Datetime']}'
                  )
        """
        cursor.execute(cell_log_query)
        connection.commit()

except Error as e:
    print(f"The error '{e}' occurred")

finally:
    if 'cursor' in locals() and cursor is not None:
        cursor.close()
    if 'connection' in locals() and connection is not None:
        connection.close()

The error '1054 (42S22): Unknown column 'None' in 'field list'' occurred

### 모델 저장

In [49]:
# Save the trained model to a file
with open('isolation_forest_model-0.2.0.pkl', 'wb') as file:
    pickle.dump(model, file)